sudo: required
services: docker

language: python

# Build matrix
python:
  - "2.7"

install:
  - pip install -r requirements.txt

script:
  - ./build/run-tests.sh
  - ./build/run-linter.sh
  - ./build/build-docs.sh
