sudo: required
services: docker

language: python

# Build matrix
python:
  - "2.7"

install:
  - pip install -r requirements.txt

script:
  - ./build/test.sh
  - ./build/run-linter.sh
  - ./build/build-docs.sh

notifications:
  email:
    on_success: never
    on_failure: always
