site_name: Dnnamo
repo_url: https://github.com/rdadolf/dnnamo
site_description: 'Dnnamo: Tools for Analysis, Modeling, and Optimization of Deep Neural Networks'
google_analytics: ['UA-29492860-4', 'auto']

site_dir: 'deploy'
theme: 'readthedocs'
extra_css: [assets/dnnamo.css]

pages:
# * = not even close to being done
  - 'Overview*': index.md
  - 'Getting Started':
    - 'Installation': install.md
    - 'Quick Start': quickstart.md
    - 'Tools*': tool_list.md
    - 'Models*': model_list.md
    - 'Devices*': device_list.md
  - 'Developing with NNModel':
    - 'Frameworks*': dev/frameworks.md
    - 'Models*': dev/models.md
    - 'Primops*': dev/primops.md
    - 'DGraphs*': dev/dgraphs.md
#- 'Constraints': ?
    - 'Devices*': dev/devices.md
  - 'Extending NNModel':
    - 'Building a New Tool*': new_tool.md
    - 'Importing a New Model': import.md
